### ISSUE TITLE
Org quota

### ISSUE THREAD

**Issue by pdev1989** [bosh-prometheus/cf_exporter#35]
Hi 
As far as I could see this exporter does not scrape the metrics of org quota for each org & current org quota usage. Would this be added in the future, please ?

Regards.

**Comment by Infra-Red** [comment]
Hi @pdev1989 !
CF exporter doesn't scrape this metric because it's configured on the deployment level through the `maximum_app_disk_in_mb` cc property, so currently there is no way to retrieve this setting using CF API. 
https://github.com/cloudfoundry/capi-release/blob/c269265ab3e80b566d33226729c07868aaee28af/jobs/cloud_controller_ng/spec#L729-L731
